//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public Information()
        {
            this.Station = new HashSet<Station>();
        }
    
        public int i_no { get; set; }
        public string stationname { get; set; }
        public string address { get; set; }
        public Nullable<int> x { get; set; }
        public Nullable<int> y { get; set; }
    
        public virtual ICollection<Station> Station { get; set; }
    }
}
