//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITTRAINEntities1 : DbContext
    {
        public ITTRAINEntities1()
            : base("name=ITTRAINEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Division> Division { get; set; }
        public DbSet<Information> Information { get; set; }
        public DbSet<Reservation> Reservation { get; set; }
        public DbSet<Station> Station { get; set; }
        public DbSet<User> User { get; set; }
    }
}
