//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int r_no { get; set; }
        public Nullable<int> u_no { get; set; }
        public Nullable<System.DateTime> r_date { get; set; }
        public Nullable<int> r_start { get; set; }
        public Nullable<int> r_end { get; set; }
        public Nullable<System.TimeSpan> r_time { get; set; }
        public Nullable<int> r_car { get; set; }
        public string r_seat { get; set; }
    
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
        public virtual User User { get; set; }
    }
}
