//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public Station()
        {
            this.Reservation = new HashSet<Reservation>();
            this.Reservation1 = new HashSet<Reservation>();
        }
    
        public int s_no { get; set; }
        public Nullable<int> s_code { get; set; }
        public Nullable<int> i_no { get; set; }
    
        public virtual Information Information { get; set; }
        public virtual ICollection<Reservation> Reservation { get; set; }
        public virtual ICollection<Reservation> Reservation1 { get; set; }
    }
}
